CC=g++
CFLAGS=-c -Wall -fPIC
LDFLAGS=-shared
INC=-I inc -I math/inc
SOURCES=SMath.cpp
OBJECTS=$(SOURCES:.cpp=.o)
LIB=libSMath.so

vpath %.cpp src

all: $(OBJECTS) $(LIB)
	@echo "$@ done"
	
print:
	@echo "start $@:"
	@echo "$@ done"
	
$(LIB): $(OBJECTS) 
	@echo
	@echo "start generating $@"
	$(CC) $(LDFLAGS) $(INC) obj/$(OBJECTS) -lgmp -o lib/$@
	@echo "$@ done"
	@echo

%.o: %.cpp
	$(CC) $(CFLAGS) $(INC) -o obj/$@ $<

clean:
	rm -rf obj/*
	rm -rf lib/*
